### PR TITLE
Fixes bundle install error where unable to reset to revision

### PR DESCRIPTION
**Pull request by martinseener**
updated revision to the latest of that branch

### CODE REVIEW

**Comment by martinseener** [comment]
Also added before_install apt package install so the do_postgres gem can be built (requires native extensions). Build still fails for other reasons which need to befixed

**Comment by lazyatom** [comment]
Thanks for working on this!

I wonder if you'd mind squashing the commits down to just two/three - one to fix the recap revision, and the others to add the postgres and redis dependencies for Travis?

**Comment by martinseener** [comment]
Hi, if you tell me how i can do this (squashing them down), then i will happily do this (btw. with all those commits, the travis build will be green again ;))

**Comment by martinseener** [comment]
Squashed them down to 3 distinct commits. Hope its fine. The build should be green, so you can merge that

**Comment by lazyatom** [comment]
Thanks!

**Comment by martinseener** [comment]
You're welcome. Btw. we're using the backend server with an Apache2 Proxy on HTTPS now successfully with the commits above and PhantomJS 2.0!

**Comment by lazyatom** [comment]
Nice. Is your usage of it something public that I can take a look at?

**Comment by martinseener** [comment]
Wrote you a mail to james@lazyatom.com ;)

**Pull request merged**
